[package]
name = "twsearch-ffi"
version.workspace = true
license.workspace = true
edition.workspace = true
description = "Twizzle Search FFI â€” C FFI bindings for twsearch"

[features]
default = []

[dependencies]
cbindgen = "0.26.0"
twsearch = { path = "../rs", version = "0.6.5" }

[lib]
path = "./lib.rs"
crate-type = ["cdylib"]

[dev-dependencies]
cubing = { workspace = true }
libloading = "0.8.1"
test-cdylib = "1.1.0"
