[package]
name = "twsearch"
version.workspace = true
license.workspace = true
edition.workspace = true
description = "Twizzle Search â€” Twisty puzzle search library"

[features]
default = []

[dependencies]
cityhasher = "0.1.0"
clap = { version = "4.3.24", features = ["derive"] }
clap_complete = "4.3.2"
cubing = { version = "0.9.0", path = "../../../cubing.rs" }
derive_more = "0.99.17"
indicatif = "0.17.6"
instant = { version = "0.1.12", features = ["wasm-bindgen"] }
lazy_static = "1.4.0"
rand = "0.8.5"
rouille = "3.6.2"
serde = { version = "1.0.186", features = ["derive", "rc"] }
serde_json = "1.0.105"
thousands = "0.2.0"

[[bin]]
name = "twsearch"
path = "./_cli/main.rs"

[lib]
path = "./mod.rs"
crate-type = ["cdylib", "rlib"]
